msys2/msys2-tests

- .github/workflows/main.yml
- python/setuptools-cext/.gitignore
- python/setuptools-cext/cwrapper.c
- python/setuptools-cext/setup.py
- python/setuptools-cext/test.py
- python/setuptools-cext/test.sh
Builds a C extension and tries to load it.
> Add some basic setuptools build tests

- toolchain/tests/meson.build
- toolchain/tests/windres.c
- toolchain/tests/windres.rc
the .rc file is based on the glib one
> Add a windres test

- .github/workflows/main.yml
So we can test clang in combination with binutils, libstdc++
> Add a ucrt64+clang job

- .github/workflows/main.yml
- toolchain/custom/test-libc++-static.cc
- toolchain/custom/test.sh
- toolchain/test.sh
See https://github.com/msys2/MINGW-packages/pull/12042
> Add a test for gnu strip breaking libc++

- toolchain/meson/tests/meson.build
- toolchain/meson/tests/undef_memrchr.c
See https://github.com/msys2/MINGW-packages/pull/13125
> Add a regression test for memrchr errors with clang

- toolchain/meson/tests/meson.build
- toolchain/meson/tests/stpcpy_fortify.c
See https://github.com/msys2/MINGW-packages/issues/5803#issuecomment-1278895379
> Add a regression test for _FORTIFY_SOURCE + stpcpy with gcc

- .github/workflows/main.yml
- rust/test.sh
See https://github.com/msys2/MINGW-packages/pull/14036
> test rust with clang32

- toolchain/meson/tests/meson.build
- toolchain/meson/tests/posix_sem.c
> Add a posix semaphore test

- .github/workflows/main.yml
- Makefile
- tools/test.sh
start it and try to show a backtrace, even if there is none.
> Add a simple gdb test

- toolchain/custom/test-libc++-static.sh
- toolchain/custom/test.sh
- toolchain/custom/test_cc_stack_size.sh
see https://github.com/msys2/MINGW-packages/pull/16968#issuecomment-1545473141
> toolchain: make sure SizeOfStackReserve is large enough for gcc

- toolchain/meson/meson_options.txt
- toolchain/meson/tests/meson.build
- toolchain/test.sh
some of them should be fixed now with newer binutils
> toolchain: run all tests with the cross toolchain

- .github/workflows/main.yml
- Makefile
- libtool/.gitignore
- libtool/mylib/Makefile
- libtool/mylib/main.c
- libtool/mylib/mylib.c
- libtool/mylib/mylib.h
- libtool/test.sh
This builds a shared and static library just with libtool
> Add a standalone libtool example

- golang/test.sh
see https://github.com/msys2/MINGW-packages/issues/18166
> golang: test if GOPROXY is set

- runtime/path_convert/src/path_conv.cpp
- runtime/path_convert/src/path_conv.h
Copies the current msys_path_conv sources from mys2-runtime.
Key change: use the pristine `posix_to_win32_path` implementation with extra polyfill moved to an anonymous namespace.
> Update runtime test

- cmake/.gitignore
- cmake/test.sh
- cmake/x86_64-w64-mingw32ucrt.cmake
- toolchain/meson/x86_64-w64-mingw32ucrt.txt
- toolchain/test.sh
Depends on https://github.com/msys2/MSYS2-packages/pull/4186
> toolchain: add cross tests for x86_64-w64-mingw32ucrt

- .github/workflows/main.yml
- Makefile
- keyring/test.sh
Test that creating the local keyring works, and that the packager keys are trusted.
> Add a test for the pacman keyring

- autotools/Makefile
> autotools: update tests for autoconf 2.72

- runtime/path_convert/src/main.cpp
- runtime/path_convert/src/path_conv.cpp
For https://github.com/msys2/msys2-runtime/pull/182
> Sync pathconv tests

- toolchain/meson/tests/ices/gcc-115038-1.cpp
- toolchain/meson/tests/ices/gcc-115038-2.cpp
- toolchain/meson/tests/ices/gcc-115038-3.c
- toolchain/meson/tests/ices/meson.build
- toolchain/meson/tests/meson.build
See https://github.com/msys2/MINGW-packages/pull/20884
> Add some tests for the recent gcc crashes

- toolchain/meson/tests/libcpp_long_double.cpp
- toolchain/meson/tests/meson.build
See https://github.com/msys2/MINGW-packages/pull/21796
> toolchain: add a test for libc++ handling of long double

- toolchain/meson/tests/meson.build
- toolchain/meson/tests/wcstok_nonconform.c
~~will fail with cygwin cross compilers still~~
> Add a test for _CRT_NON_CONFORMING_WCSTOK
